=== nickpalenchar/kitchendb/data/schemas/recipes.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://kitchendb.net/data/schemas/recipes.json",
  "title": "Recipe",
  "description": "A Recipe",
  "type": "object",
  "properties": {
    "timestamp": {
      "description": "time the recipe was submitted",
      "type": "string"
    },
    "version": {
      "description": "The version number. Always \"1\".",
      "type": "string"
    },
    "name": {
      "description": "Human readable name of the recipe.",
      "type": "string"
    },
    "summary": {
      "description": "short summary that goes before the recipe.",
      "type": "string",
      "maxLength": 480
    },
    "yields": {
      "description": "number of servings recipe makes",
      "type": "integer",
      "minimum": 1
    },
    "yieldsUnit": {
      "description": "The unit of what the recipe yields",
      "type": "string"
    },
    "categories": {
      "description": "list of categories for further recipe refinement",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "side dish",
          "breakfast",
          "lunch",
          "dinner",
          "appetizer",
          "dessert",
          "drink",
          "pasta",
          "cocktail",
          "mocktail",
          "vegetarian",
          "vegan",
          "gluten-free",
          "seasonal",
          "cookout",
          "crock pot",
          "soup",
          "snack",
          "condiment/dressing"
        ]
      }
    },
    "originalSource": {
      "description": "Link to the original source of the recipe",
      "type": "string"
    },
    "ingredients": {
      "description": "List of ingredients, divided into one or more sections",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "sectionTitle": {
            "description": "Title of the section. If only one section, use \"\"",
            "type": "string"
          },
          "ingredients": {
            "description": "The ingredients for the section",
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "properties": {
                "unit": {
                  "description": "unit of measurement",
                  "type": "string",
                  "enum": [
                    "lb",
                    "oz",
                    "g",
                    "cup",
                    "fl oz",
                    "ml",
                    "pint",
                    "tsp",
                    "tbsp",
                    "pinch",
                    "kg",
                    "gal",
                    "liter"
                  ]
                },
                "customUnit": {
                  "description": "use for non-standard unit of measurement",
                  "type": "string"
                },
                "amount": {
                  "description": "the quantity of the measurement",
                  "type": "array", "minItems": 1, "maxLength": 2 
                },
                "ingredient": {
                  "description": "The name of the ingredient",
                  "type": "string"
                },
                "modifier": {
                  "description": "A way to arrange or prep ingredient. i.e. 'chopped'",
                  "type": "string"
                }
              },
              "required": [
                "ingredient"
              ]
            }
          }
        },
        "required": [
          "sectionTitle",
          "ingredients"
        ]
      }
    },
    "steps": {
      "description": "The series of steps for making the recipe",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "description": "A group of steps",
        "properties": {
          "sectionTitle": {
            "description": "Title of the section. If only one section, use \"\"",
            "type": "string"
          },
          "steps": {
            "type": "array",
            "description": "steps in the section",
            "minItems": 1,
            "items": {
              "type": "string",
              "description": "A single step"
            }
          }
        }
      }
    },
    "media": {
      "type": "array",
      "description": "online media related to the recipe, such as videos or photos",
      "items": {
        "type": "object",
        "description": "media item",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "photo",
              "video",
              "youtube",
              "vimeo",
              "post",
              "other"
            ]
          },
          "link": {
            "description": "usually a hyperlink to the media source",
            "type": "string"
          },
          "comment": {
            "description": "free-use text for providing additional context to item",
            "type": "string"
          }
        },
        "required": ["type"]
      }
    },
    "attribution": {
      "description": "properties relating to author attribution and credit",
      "type": "object",
      "properties": {
        "name": {
          "description": "Real or username",
          "type": "string"
        },
        "links": {
          "description": "social media and other links relating to the author (not necessarily the recipe)",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "link": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  },
  "required": [
    "version",
    "name",
    "ingredients",
    "steps",
    "timestamp"
  ]
}

=== nickpalenchar/kitchendb/data/recipes/redditʼs-"murder-cookies"-modern-version.json
{
  "version": "1",
  "name": "Reddit's \"Murder Cookies\" (modern version)",
  "summary": "From a 1930's recipe where the baker's neighbor got murdered, now repopularized on reddit under a name you can't forget! This recipe is updated with more common ingredients.",
  "categories": ["dessert"],
  "steps": [
    {
      "sectionTitle": "",
      "steps": [
        "Preheat the oven to 350 degrees F.",
        "Combine sugar, butter, molasses and egg with an electric beater.",
        "In a separate bowl, sift together dry ingredients (flour, salt, baking soda, cinnamon, nutmeg, and allspice).",
        "Mix in parts of the dry ingredients and milk into the first bowl, in about thirds.",
        "Scoop batter by 1 tablespoon (slightly overflowing) onto greased cookie sheet.",
        "Bake for 12-14 minutes."
      ]
    }
  ],
  "ingredients": [
    {
      "sectionTitle": "",
      "ingredients": [
        {
          "amount": [
            1.5
          ],
          "unit": "cup",
          "ingredient": "sugar"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "cup",
          "ingredient": "butter",
          "modifier": "softened"
        },
        {
          "amount": [
            0.5
          ],
          "unit": "cup",
          "ingredient": "molasses"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "egg"
        },
        {
          "amount": [
            3.5
          ],
          "unit": "cup",
          "ingredient": "flour"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "tsp",
          "ingredient": "salt"
        },
        {
          "amount": [
            2.5
          ],
          "unit": "tsp",
          "ingredient": "baking soda"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "tsp",
          "ingredient": "cinnamon"
        },
        {
          "amount": [
            0.5
          ],
          "unit": "tsp",
          "ingredient": "nutmeg"
        },
        {
          "amount": [
            0.5
          ],
          "unit": "tsp",
          "ingredient": "allspice"
        },
        {
          "amount": [
            0.25
          ],
          "unit": "cup",
          "ingredient": "whole milk"
        }
      ]
    }
  ],
  "timestamp": "11/8/2022 21:55:28"
}

=== nickpalenchar/kitchendb/data/recipes/haba-jala-basco-hot-sauce.json
{
  "version": "1",
  "name": "Haba-Jala-Basco Hot Sauce",
  "summary": "Easy home made hot sauce",
  "categories": ["condiment/dressing"],
  "steps": [
    {
      "sectionTitle": "",
      "steps": [
        "Remove the stems from the peppers and cut them in half, lengthwise. Remove and discard the seeds and ribs according to desired heat levels. Roughly chop the peppers into pieces approximately 2\u2033 in size.",
        "NOT OPTIONAL: WEAR GLOVES!",
        "Put the chopped peppers and the rest of the ingredients in a medium-sized sauce pan. Bring it to a boil, then cover and reduce to a lightly-bubbling simmer for 15-20 minutes. Be careful when removing the lid \u2014 the vinegar steam is potent!",
        "While still hot, carefully pour everything into a powerful blender. Slowly increase speed from low to high until the sauce is completely smooth. This may require a few minutes of blending.",
        "Pour still-hot hot sauce through a strainer into funnel set up in the mouth of your hot sanitized hot sauce bottle. You may need to do this in a few batches. Use a small spatula to press the sauce through the strainer, occasionally lifting the strainer to scrape the sauce off the bottom and into the funnel.",
        "Seal the bottle tightly and let the hot sauce cool to room temperature, then store in the refrigerator or at room temperature for up to 8 months"
      ]
    }
  ],
  "ingredients": [
    {
      "sectionTitle": "",
      "ingredients": [
        {
          "amount": [
            4.0
          ],
          "customUnit": "",
          "ingredient": "8-oz hot sauce bottles"
        },
        {
          "ingredient": "Rubber Gloves!!"
        },
        {
          "amount": [
            10.0
          ],
          "unit": "oz",
          "ingredient": "Combined Habaneros",
          "modifier": "Jalape\u00f1os, and Tabasco Peppers (weight is after chopping the peppers and removing desired seeds)"
        },
        {
          "amount": [
            4.0
          ],
          "unit": "oz",
          "ingredient": "medium shallots (about 2-3 bulbs",
          "modifier": "cut into quarters)"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "oz",
          "ingredient": "garlic cloves (about 5 cloves",
          "modifier": "smashed)"
        },
        {
          "amount": [
            5.0
          ],
          "customUnit": "",
          "ingredient": "whole peppercorns"
        },
        {
          "amount": [
            2.0
          ],
          "unit": "tsp",
          "ingredient": "pickling salt"
        },
        {
          "amount": [
            6.0
          ],
          "unit": "oz",
          "ingredient": "distilled white vinegar (0.75 cup)"
        }
      ]
    }
  ],
  "timestamp": "11/12/2022 9:00:52"
}

=== nickpalenchar/kitchendb/data/recipes/winter-squash-and-wild-mushroom-curry.json
{
  "version": "1",
  "name": "Winter Squash and Wild Mushroom Curry",
  "summary": "",
  "steps": [
    {
      "sectionTitle": "",
      "steps": [
        "in a wide skillet, heat oil over medium-high. When hot, add squash cubes in one layer. Season with salt and pepper. Cook for about 2 minutes, letting cubes brown slightly, then flip and cook for 2 minutes more. Use a slotted spoon to lift squash out, and set aside.",
        "Cut a lengthwise slit in each chile to open it, but leave whole. (This helps the chiles heat the sauce without making it too spicy.)",
        "Add shallots, salt lightly and cook, stirring, 1 minute. Add mustard seeds, cumin seeds and curry leaves, if using, and let sizzle for 30 seconds, then add garlic, coriander, cayenne, turmeric and chiles. Stir well and cook for 30 seconds more.",
        "Add mushrooms, season with salt and toss to coat. Cook, stirring, until mushrooms begin to soften, about 5 minutes.",
        "Return squash cubes to skillet, stir in coconut milk and bring to a simmer. Lower heat to medium and simmer for another 5 minutes. If mixture looks dry, thin with a little water. Taste and season with salt.",
        "Before serving, stir in lime juice. Transfer to a warm serving dish and garnish with cilantro."
      ]
    }
  ],
  "ingredients": [
    {
      "sectionTitle": "",
      "ingredients": [
        {
          "amount": [
            3.0
          ],
          "unit": "tbsp",
          "ingredient": "vegetable oil"
        },
        {
          "amount": [
            0.5
          ],
          "customUnit": "",
          "ingredient": "unces butternut or other winter squash",
          "modifier": "peeled and cut into 1/2-inch pieces"
        },
        {
          "ingredient": "Kosher salt"
        },
        {
          "ingredient": "Black pepper"
        },
        {
          "amount": [
            1.0,
            2.0
          ],
          "customUnit": "",
          "ingredient": "small green chiles",
          "modifier": "such as jalape\u00f1o or serrano"
        },
        {
          "amount": [
            3.0
          ],
          "customUnit": "",
          "ingredient": "medium shallots or 1 small onion",
          "modifier": "finely diced"
        },
        {
          "amount": [
            0.5
          ],
          "unit": "tsp",
          "ingredient": "black mustard seeds"
        },
        {
          "amount": [
            0.5
          ],
          "unit": "tsp",
          "ingredient": "cumin seeds"
        },
        {
          "ingredient": "Handful of fresh or frozen curry leaves (optional)"
        },
        {
          "amount": [
            2.0
          ],
          "customUnit": "",
          "ingredient": "garlic cloves",
          "modifier": "minced"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "tsp",
          "ingredient": "ground coriander"
        },
        {
          "ingredient": "Pinch of ground cayenne"
        },
        {
          "amount": [
            0.5
          ],
          "unit": "tsp",
          "ingredient": "ground turmeric"
        },
        {
          "amount": [
            0.12
          ],
          "customUnit": "",
          "ingredient": "und mushrooms",
          "modifier": "preferably a mix of cultivated and wild, trimmed and sliced 1/8-inch thick"
        },
        {
          "amount": [
            0.75
          ],
          "unit": "cup",
          "ingredient": "coconut milk"
        },
        {
          "amount": [
            2.0
          ],
          "unit": "tbsp",
          "ingredient": "lime juice"
        },
        {
          "ingredient": "Cilantro sprigs, for garnish"
        }
      ]
    }
  ],
  "timestamp": "11/4/2022 22:56:00"
}

=== nickpalenchar/kitchendb/data/recipes/strawberry-"clif"-bars.json
{
  "version": "1",
  "name": "Strawberry \"Clif\" Bars",
  "summary": "Immatation clif bars",
  "steps": [
    {
      "sectionTitle": "",
      "steps": [
        "In a blender or food processor, blend the frozen berries so they are powdery or in tiny pieces. Stir all dry ingredients together in a bowl, then stir in nut butter. Add in honey/agave and mix until sticky dough forms.",
        "Line a pan with parchment paper, add the mix and spread evenly. Freeze for 1 hour or longer.",
        "Remove from freezer and cut into bars.",
        "Store at room temperature or in the fridge for 2-3 days, or freeze up to a month."
      ]
    }
  ],
  "ingredients": [
    {
      "sectionTitle": "",
      "ingredients": [
        {
          "amount": [
            0.75
          ],
          "unit": "cup",
          "ingredient": "quick oats or rolled oats"
        },
        {
          "amount": [
            0.12
          ],
          "unit": "tsp",
          "ingredient": "salt"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "cup",
          "ingredient": "freeze-dried raspberries or strawberries"
        },
        {
          "amount": [
            0.33
          ],
          "unit": "cup",
          "ingredient": "peanut butter or nut butter of choice"
        },
        {
          "amount": [
            0.25
          ],
          "unit": "cup",
          "ingredient": "agave or honey"
        }
      ]
    }
  ],
  "timestamp": "11/4/2022 22:54:34"
}

=== nickpalenchar/kitchendb/data/recipes/beef-lo-mein.json
{
  "version": "1",
  "name": "Beef Lo Mein",
  "summary": "",
  "steps": [
    {
      "sectionTitle": "",
      "steps": [
        "Cook pasta in salted boiling water according to package\u2019s instruction.",
        "Mince garlic, prepare the rest of vegetables.",
        "Add 3 TBS sesame oil in a large pan over medium-high heat. Add garlic. Stir occasionally.",
        "Slice chicken into thin pieces. Add chicken in the pan, cook until slightly white.",
        "Add vegetables, stir occasionally.",
        "Mix all sauce ingredients together. Add into the pan.",
        "Stir occasionally until slightly thicken.",
        "Add cooked pasta. Stir for a minute or until the sauce is almost dry. Remove from heat.",
        "Serve hot, sprinkle with some sesame seed for garnishing."
      ]
    }
  ],
  "ingredients": [
    {
      "sectionTitle": "Pasta dish",
      "ingredients": [
        {
          "amount": [
            3.0
          ],
          "customUnit": "",
          "ingredient": "cloves garlic"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "large carrot",
          "modifier": "3 oz (85g)"
        },
        {
          "amount": [
            10.0
          ],
          "unit": "oz",
          "ingredient": "- 16 oz (283 g - 463g) broccoli"
        },
        {
          "amount": [
            3.0
          ],
          "unit": "oz",
          "ingredient": "snow peas"
        },
        {
          "amount": [
            3.0
          ],
          "unit": "tbsp",
          "ingredient": "sesame oil"
        }
      ]
    },
    {
      "sectionTitle": "sauce",
      "ingredients": [
        {
          "amount": [
            0.25
          ],
          "unit": "cup",
          "ingredient": "soy sauce"
        },
        {
          "amount": [
            0.25
          ],
          "unit": "cup",
          "ingredient": "water"
        },
        {
          "amount": [
            3.0
          ],
          "unit": "tbsp",
          "ingredient": "sesame oil"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "tbsp",
          "ingredient": "sugar"
        },
        {
          "amount": [
            0.5
          ],
          "unit": "tsp",
          "ingredient": "ground pepper"
        },
        {
          "amount": [
            0.25
          ],
          "unit": "tsp",
          "ingredient": "red pepper flakes",
          "modifier": "optional for a kick"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "tsp",
          "ingredient": "ground ginger"
        }
      ]
    }
  ],
  "timestamp": "11/4/2022 23:00:00"
}

=== nickpalenchar/kitchendb/data/recipes/cote-nyc-steak-marinade.json
{
  "version": "1",
  "name": "Cote NYC Steak Marinade",
  "summary": "Steak the way they make it in would famous nyc steakhouses",
  "steps": [
    {
      "sectionTitle": "",
      "steps": [
        "Using a knife, make 3/4 slits in the meat, about 1/2 inch apart.",
        "Puree all puree ingredients, then rub all over the steak. Place in the fridge for at least 30 minutes.",
        "Combine all soy ingredients, being sure to stir the sugar in well. Add to the steak, keep in fridge for another 3-4 hours.",
        "Cook. Grilling recommended.",
        "Optional. Finish with chopped green onions"
      ]
    }
  ],
  "ingredients": [
    {
      "sectionTitle": "Meat",
      "ingredients": [
        {
          "ingredient": "Steak or Beef Steak"
        }
      ]
    },
    {
      "sectionTitle": "Puree Marinade",
      "ingredients": [
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "pear",
          "modifier": "chopped"
        },
        {
          "amount": [
            0.5
          ],
          "customUnit": "",
          "ingredient": "onion",
          "modifier": "chopped"
        },
        {
          "ingredient": "Thumbnail size of ginger, zested"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "tbsp",
          "ingredient": "minced garlic"
        }
      ]
    },
    {
      "sectionTitle": "Soy Marinade",
      "ingredients": [
        {
          "amount": [
            2.0
          ],
          "unit": "cup",
          "ingredient": "soy sauce"
        },
        {
          "amount": [
            2.0
          ],
          "unit": "cup",
          "ingredient": "water"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "cup",
          "ingredient": "Mirin"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "cup",
          "ingredient": "Sugar"
        }
      ]
    }
  ],
  "timestamp": "11/4/2022 15:48:21",
  "categories": [
    "dinner",
    "cookout",
    "gluten-free"
  ]
}
