=== nickpalenchar/kitchendb/data/schemas/recipes.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://kitchendb.net/data/schemas/recipes.json",
  "title": "Recipe",
  "description": "A Recipe",
  "type": "object",
  "properties": {
    "timestamp": {
      "description": "time the recipe was submitted",
      "type": "string"
    },
    "version": {
      "description": "The version number. Always \"1\".",
      "type": "string"
    },
    "name": {
      "description": "Human readable name of the recipe.",
      "type": "string"
    },
    "summary": {
      "description": "short summary that goes before the recipe.",
      "type": "string",
      "maxLength": 480
    },
    "yields": {
      "description": "number of servings recipe makes",
      "type": "integer",
      "minimum": 1
    },
    "yieldsUnit": {
      "description": "The unit of what the recipe yields",
      "type": "string"
    },
    "categories": {
      "description": "list of categories for further recipe refinement",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "side dish",
          "breakfast",
          "lunch",
          "dinner",
          "appetizer",
          "dessert",
          "drink",
          "pasta",
          "cocktail",
          "mocktail",
          "vegetarian",
          "vegan",
          "gluten-free",
          "seasonal",
          "cookout",
          "crock pot",
          "soup",
          "snack",
          "condiment/dressing"
        ]
      }
    },
    "originalSource": {
      "description": "Link to the original source of the recipe",
      "type": "string"
    },
    "ingredients": {
      "description": "List of ingredients, divided into one or more sections",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "sectionTitle": {
            "description": "Title of the section. If only one section, use \"\"",
            "type": "string"
          },
          "ingredients": {
            "description": "The ingredients for the section",
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "properties": {
                "unit": {
                  "description": "unit of measurement",
                  "type": "string",
                  "enum": [
                    "lb",
                    "oz",
                    "g",
                    "cup",
                    "fl oz",
                    "ml",
                    "pint",
                    "tsp",
                    "tbsp",
                    "pinch",
                    "kg",
                    "gal",
                    "liter"
                  ]
                },
                "customUnit": {
                  "description": "use for non-standard unit of measurement",
                  "type": "string"
                },
                "amount": {
                  "description": "the quantity of the measurement",
                  "type": "array", "minItems": 1, "maxLength": 2 
                },
                "ingredient": {
                  "description": "The name of the ingredient",
                  "type": "string"
                },
                "modifier": {
                  "description": "A way to arrange or prep ingredient. i.e. 'chopped'",
                  "type": "string"
                }
              },
              "required": [
                "ingredient"
              ]
            }
          }
        },
        "required": [
          "sectionTitle",
          "ingredients"
        ]
      }
    },
    "steps": {
      "description": "The series of steps for making the recipe",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "description": "A group of steps",
        "properties": {
          "sectionTitle": {
            "description": "Title of the section. If only one section, use \"\"",
            "type": "string"
          },
          "steps": {
            "type": "array",
            "description": "steps in the section",
            "minItems": 1,
            "items": {
              "type": "string",
              "description": "A single step"
            }
          }
        }
      }
    },
    "media": {
      "type": "array",
      "description": "online media related to the recipe, such as videos or photos",
      "items": {
        "type": "object",
        "description": "media item",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "photo",
              "video",
              "youtube",
              "vimeo",
              "post",
              "other"
            ]
          },
          "link": {
            "description": "usually a hyperlink to the media source",
            "type": "string"
          },
          "comment": {
            "description": "free-use text for providing additional context to item",
            "type": "string"
          }
        },
        "required": ["type"]
      }
    },
    "attribution": {
      "description": "properties relating to author attribution and credit",
      "type": "object",
      "properties": {
        "name": {
          "description": "Real or username",
          "type": "string"
        },
        "links": {
          "description": "social media and other links relating to the author (not necessarily the recipe)",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "link": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  },
  "required": [
    "version",
    "name",
    "ingredients",
    "steps",
    "timestamp"
  ]
}

=== nickpalenchar/kitchendb/data/recipes/earl-grey-blackberry-scones-with-lemon-glaze.json
{
  "version": "1",
  "name": "Earl Grey Blackberry Scones with Lemon Glaze",
  "summary": "Makes 16 scones. Keep all ingredients chilled until needed.",
  "steps": [
    {
      "sectionTitle": "",
      "steps": [
        "Preheat oven to 400 F. Move baking tray to upper 1/3 of the oven. Line a baking tray with parchment paper and set aside.",
        "Grind 1 1/4 tbs earl grey tea in a small blender or with a mortar and pestle.",
        "In a large mixing bowl, sift together flour, sugar, tea, baking powder, baking soda, and salt. Discard any pieces that don\u2019t go through sieve with ease. Cut in butter using a pastry cutter or your fingers until the mixture is course and butter is pea-sized or smaller. Place dry mixture in the freezer or refrigerator for 5 minutes while you prepare the wet ingredients.",
        "In a small mixing bowl, combine egg and buttermilk and beat lightly with a fork. Rinse and dry the blackberries.",
        "Take the dry mixture out of the freezer or refrigerator. Mix wet and dry mixtures with a spoon until combined. Continue to combine with your hands until a soft dough is formed. Knead by folding the dough in half 3-5 times.",
        "Add blackberries and continue to fold until blackberries are combined. The blackberries may get crushed a bit, that\u2019s okay. Add more flour as needed. Don\u2019t overwork.",
        "Shape dough to a 1 inch thickness. Cut dough into 2 inch circles using a round pastry cutter or cut into 2 inch squares with a knife. Reshape excess dough, fold and re-cut.",
        "Place scones onto your prepared baking tray. Place tray in the freezer for 5 minutes so that the butter can firm up again.",
        "Brush scones with buttermilk and sprinkle with granulated sugar before placing in the oven. Bake for 16-20 minutes until tops are golden brown. Place scones on a metal rack with a piece of parchment paper underneath until scones are cool.",
        "Prep the glaze. Mix powdered sugar, lemon juice, vanilla and lemon zest with a fork until smooth. Add extra lemon juice or powdered sugar as needed until you get the right consistency.",
        "Drizzle glaze evenly onto the scones, allowing excess to drip onto the parchment paper. Let scones sit for 10-15 minutes until glaze sets.",
        "Serve as soon as possible. Scones will keep about 2 days. You can freeze extra scones (wrap in saran wrap) and reheat later as needed."
      ]
    }
  ],
  "ingredients": [
    {
      "sectionTitle": "Scones",
      "ingredients": [
        {
          "amount": [
            3.25
          ],
          "unit": "cup",
          "ingredient": "all-purpose flour \u2014 plus extra flour for kneading"
        },
        {
          "amount": [
            0.3
          ],
          "unit": "cup",
          "ingredient": "granulated sugar"
        },
        {
          "amount": [
            1.5
          ],
          "unit": "tbsp",
          "ingredient": "earl grey tea",
          "modifier": "ground until fine"
        },
        {
          "amount": [
            2.5
          ],
          "unit": "tsp",
          "ingredient": "baking powder"
        },
        {
          "amount": [
            0.5
          ],
          "unit": "tsp",
          "ingredient": "baking soda"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "tsp",
          "ingredient": "salt"
        },
        {
          "amount": [
            0.75
          ],
          "unit": "cup",
          "ingredient": "cold unsalted butter"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "large egg",
          "modifier": "lightly beaten"
        },
        {
          "amount": [
            0.75
          ],
          "unit": "cup",
          "ingredient": "cold buttermilk"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "cup",
          "ingredient": "fresh blackberries"
        },
        {
          "ingredient": "Extra buttermilk & granulated sugar to top scones before baking"
        }
      ]
    },
    {
      "sectionTitle": "Glaze",
      "ingredients": [
        {
          "amount": [
            1.0
          ],
          "unit": "cup",
          "ingredient": "powdered sugar"
        },
        {
          "amount": [
            1.5
          ],
          "unit": "tbsp",
          "ingredient": "lemon juice"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "tsp",
          "ingredient": "vanilla"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "lemon",
          "modifier": "the Zest of"
        }
      ]
    }
  ],
  "timestamp": "10/3/2022 17:40:58"
}

=== nickpalenchar/kitchendb/data/recipes/vegitarian-minnissota-chili.json
{
  "version": "1",
  "name": "Vegetarian Minnesota Chili",
  "summary": "From \"Eat and Run.\" Vegetarian chili never tasted so hearty.",
  "steps": [
    {
      "sectionTitle": "",
      "steps": [
        "Finely chop onion, red and green peppers, and carrots. Add with corn into pot on medium to medium low heat. Simmer for 10 minutes or until tender.",
        "Add remaining ingredients except cilantro and simmer over medium-low heat, covered, for 30 minutes.",
        "uncover and stir and simmer for an additional 20-30 minutes."
      ]
    }
  ],
  "ingredients": [
    {
      "sectionTitle": "",
      "ingredients": [
        {
          "amount": [
            2.0
          ],
          "unit": "tbsp",
          "ingredient": "coconut oil or olive oil"
        },
        {
          "amount": [
            3.0
          ],
          "customUnit": "",
          "ingredient": "garlic cloves",
          "modifier": "minced"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "cup",
          "ingredient": "finely chopped onion"
        },
        {
          "amount": [
            8.0,
            10.0
          ],
          "customUnit": "",
          "ingredient": "medium mushrooms",
          "modifier": "finely chopped"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "green bell pepper",
          "modifier": "finely chopped"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "red bell pepper",
          "modifier": "finely chopped"
        },
        {
          "amount": [
            2.0,
            3.0
          ],
          "customUnit": "",
          "ingredient": "full carrots",
          "modifier": "finely chopped"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "jalapeno pepper",
          "modifier": "seeded and very finely chopped."
        },
        {
          "amount": [
            1.5
          ],
          "unit": "cup",
          "ingredient": "frozen corn kernals (maybe more)"
        },
        {
          "amount": [
            2.0
          ],
          "unit": "tsp",
          "ingredient": "ground cumin"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "tsp",
          "ingredient": "coriander"
        },
        {
          "amount": [
            2.0
          ],
          "unit": "tbsp",
          "ingredient": "chili powder"
        },
        {
          "amount": [
            2.0
          ],
          "unit": "tbsp",
          "ingredient": "sea salt",
          "modifier": "plus more to taste"
        },
        {
          "ingredient": "black pepper to taste"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "28-oz can diced tomatoes"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "15-oz can tomato puree"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "15-oz can kidney beans",
          "modifier": "drained"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "15-oz can red beans",
          "modifier": "drained"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "15-oz can black beans",
          "modifier": "drained"
        },
        {
          "amount": [
            2.0
          ],
          "unit": "cup",
          "ingredient": "water (maybe a little less for chunkier)"
        },
        {
          "amount": [
            0.5
          ],
          "unit": "cup",
          "ingredient": "dry bulger wheat",
          "modifier": "hot sauce or cayenne pepper (optional)"
        },
        {
          "amount": [
            0.25
          ],
          "unit": "cup",
          "ingredient": "minced fresh cilantro",
          "modifier": "for garnish."
        }
      ]
    }
  ],
  "timestamp": "11/11/2022 9:03:36",
  "categories": [
    "soup",
    "vegetarian",
    "vegetarian"
  ]
}

=== nickpalenchar/kitchendb/data/recipes/white-bean-potato-soup.json
{
  "version": "1",
  "name": "White Bean Potato Soup",
  "summary": "The perfect transition from Summer to Fall: summer notes and flavors with the comfort of Fall SOUP",
  "steps": [
    {
      "sectionTitle": "",
      "steps": [
        "If using a leek, make sure to cut the root and woody dark green top off. Cut the remaining white and light green stalk lengthwise and rinse between the layers under running water to remove any dirt. Thinly slice it and then warm a soup pot over medium heat. ",
        "Heat up the oil in the pot and then add in the leeks, carrots, celery with a pinch of salt and saut\u00e9 until softened, about 3-5 minutes. Then, add in the garlic and red pepper flakes and stir until fragrant, about 1-2 minutes. ",
        "To the pan, add in the nutritional yeast, thyme, mustard, and give a good stir to combine. Next, pour in the potatoes and beans, mix again to fully coat in the mixture. ",
        "Pour in the vegetable broth and add in the bay leaves. Then, bring your pot to a boil and reduce to a simmer for 15-20 minutes, making sure the potato is cooked through. ",
        "Remove the soup from heat and use an immersion blender to blend a small portion of the soup to help thicken it. ",
        "If adding miso, take a spoonful of soup from the pot and place into a small bowl. Use this to mix your miso paste in until smooth, then pour back into the soup. ",
        "Stir in the spinach, dill, lemon zest and juice, adjust salt and pepper to taste and serve. "
      ]
    }
  ],
  "ingredients": [
    {
      "sectionTitle": "",
      "ingredients": [
        {
          "amount": [
            1.0
          ],
          "unit": "tbsp",
          "ingredient": "Avocado Oil"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "Large Leek OR 0.5 of a medium yellow onion",
          "modifier": "diced"
        },
        {
          "amount": [
            2.0
          ],
          "customUnit": "",
          "ingredient": "stalks celery",
          "modifier": "diced"
        },
        {
          "amount": [
            2.0
          ],
          "customUnit": "",
          "ingredient": "carrots",
          "modifier": "sliced or diced"
        },
        {
          "amount": [
            5.0,
            6.0
          ],
          "customUnit": "",
          "ingredient": "cloves garlic",
          "modifier": "crushed or minced"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "tsp",
          "ingredient": "red pepper flakes",
          "modifier": "optional"
        },
        {
          "amount": [
            2.0
          ],
          "unit": "tbsp",
          "ingredient": "nutritional yeast"
        },
        {
          "amount": [
            4.0
          ],
          "customUnit": "",
          "ingredient": "sprigs fresh thyme"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "heaping tsp Dijon Mustard"
        },
        {
          "amount": [
            3.0
          ],
          "customUnit": "",
          "ingredient": "medium sized potatoes",
          "modifier": "diced into 0.5 inch cubes"
        },
        {
          "amount": [
            30.0
          ],
          "unit": "oz",
          "ingredient": "of canned white beans"
        },
        {
          "amount": [
            6.0
          ],
          "unit": "cup",
          "ingredient": "vegetable broth"
        },
        {
          "amount": [
            2.0
          ],
          "customUnit": "",
          "ingredient": "bay leaves"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "tbsp",
          "ingredient": "white miso paste"
        },
        {
          "amount": [
            2.0
          ],
          "unit": "cup",
          "ingredient": "spinach"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "lemon",
          "modifier": "(juice and zest)"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "small bunch of dill",
          "modifier": "minced (about 0.24 cups)"
        }
      ]
    }
  ],
  "timestamp": "10/3/2022 9:09:02"
}

=== nickpalenchar/kitchendb/data/recipes/turmeric-immunity-tea.json
{
  "version": "1",
  "name": "Turmeric Immunity Tea",
  "summary": "Keep your immune system strong during the winter months",
  "steps": [
    {
      "sectionTitle": "",
      "steps": [
        "Bring the water, lemon peel, ginger, turmeric, cayenne, and black pepper to a minimal simmer.",
        "Maintain a low simmer for 7 minutes. Don't let bubble or boil, as it can harm the nutrients.",
        "Take off the heat and squeeze in the lemon juice and stir in the coconut oil and honey. ",
        "Strain the tea into a container or a cup. Tea in a closed container kept in the refrigerator will keep up to 3 days."
      ]
    }
  ],
  "ingredients": [
    {
      "sectionTitle": "",
      "ingredients": [
        {
          "amount": [
            5.0
          ],
          "unit": "cup",
          "ingredient": "of water"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "lemon's peel (keep white pith intact)"
        },
        {
          "amount": [
            2.0
          ],
          "customUnit": "",
          "ingredient": "inch piece of ginger (cut into thin rounds",
          "modifier": "skin on)"
        },
        {
          "amount": [
            1.5
          ],
          "unit": "tbsp",
          "ingredient": "ground turmeric"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "pinch of cayenne pepper"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "crack of black pepper"
        },
        {
          "amount": [
            1.0
          ],
          "customUnit": "",
          "ingredient": "lemon's juice"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "tsp",
          "ingredient": "coconut oil",
          "modifier": "butter, or avocado oil"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "tbsp",
          "ingredient": "honey"
        }
      ]
    }
  ],
  "timestamp": "11/22/2022 16:21:54",
  "categories": [
    "drink",
    "seasonal"
  ],
  "attribution": {
    "name": "Bobby Parrish",
    "links": []
  }
}

=== nickpalenchar/kitchendb/data/recipes/cacio-e-pepe.json
{
  "version": "1",
  "name": "Cacio e pepe",
  "summary": "A simple yet elegant three-ingredient pasta dish",
  "steps": [
    {
      "sectionTitle": "",
      "steps": [
        "Bring a large pot of salted water to a boil.",
        "Using a microplane, finely grate 5 ounces Pecorino Romano cheese into a large bowl to get about 2 1/2 cups. Transfer 1/2 cup to a small bowl to use as garnish.",
        "Coarsely grind enough black pepper to get 1 tablespoon and use a fork to mix it into the large bowl of cheese. Drizzle in 1/3 cup ice water and use the fork to whisk it into the cheese mixture, then press the mixture against the side of the bowl, as needed, to form a thick, mostly smooth and lump-free paste; set aside.",
        "Add 1 pound dried pasta to the boiling water and cook until al dente, about 10 minutes or according to package instructions.",
        "Reserve 1/2 cup of the pasta water. Drain the pasta and working quickly, immediately add it to the large bowl of cheese paste and use the fork to vigorously stir and toss the pasta with the cheese paste, adding 1 tablespoon of the reserved pasta water at a time to loosen the paste until it evenly coats the pasta in a creamy sauce. (You\u2019ll likely use only about 2 to 3 tablespoons of the pasta water total and not use all of it.)",
        "Serve immediately, topping with the reserved grated Pecorino and a few coarse grinds of black pepper."
      ]
    }
  ],
  "ingredients": [
    {
      "sectionTitle": "",
      "ingredients": [
        {
          "amount": [
            5.0
          ],
          "unit": "oz",
          "ingredient": "Pecorino Romano cheese"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "tbsp",
          "ingredient": "coarsely ground black pepper"
        },
        {
          "amount": [
            0.33
          ],
          "unit": "cup",
          "ingredient": "ice water"
        },
        {
          "amount": [
            1.0
          ],
          "unit": "lb",
          "ingredient": "dried spaghetti",
          "modifier": "bucatini, or tonnarelli pasta"
        }
      ]
    }
  ],
  "timestamp": "11/11/2022 9:00:30"
}

=== nickpalenchar/kitchendb/data/recipes/sesame-miso-roasted-red-cabbage.json
{
  "version": "1",
  "name": "Sesame Miso Roasted Red Cabbage",
  "summary": "Excellent Side rich in nutrients",
  "steps": [
    {
      "sectionTitle": "",
      "steps": [
        "Preheat the oven to 200\u02daC/390\u02daF.",
        "Spread out the cabbage wedges on a baking tray, toss with the oil and season lightly. Roast in the oven for 30 minutes.",
        "Meanwhile make the dressing by whisking together all the ingredients.",
        "Once the 30 minutes is up, use a pastry brush to coat the cabbage pieces in the dressing then turn the oven up to 240\u02daC/465\u02daF and return them to the oven for a further 15 minutes until cooked through, caramelised and beginning to get a little crisp at the edges."
      ]
    }
  ],
  "categories": ["side dish"],
  "ingredients": [
    {
      "sectionTitle": "",
      "ingredients": [
        {
          "amount": [1.0],
          "customUnit": "",
          "ingredient": "red cabbage",
          "modifier": "cut into 8 wedges"
        },
        {
          "amount": [2.0],
          "unit": "tbsp",
          "ingredient": "rapeseed oil"
        },
        {
          "amount": [1.0],
          "unit": "pinch",
          "ingredient": "sea salt and freshly ground black pepper"
        },
        {
          "amount": [1.0],
          "unit": "tbsp",
          "ingredient": "white miso"
        },
        {
          "amount": [1.0],
          "unit": "tbsp",
          "ingredient": "mirin"
        },
        {
          "amount": [1.0],
          "unit": "tbsp",
          "ingredient": "sake"
        },
        {
          "amount": [1.5],
          "unit": "tbsp",
          "ingredient": "water"
        },
        {
          "amount": [1.0],
          "unit": "tbsp",
          "ingredient": "sugar"
        },
        {
          "amount": [1.0],
          "unit": "tbsp",
          "ingredient": "sesame seeds"
        },
        {
          "amount": [0.5],
          "unit": "tsp",
          "ingredient": "roasted sesame oil"
        }
      ]
    }
  ],
  "timestamp": "10/3/2022 17:31:54"
}

=== nickpalenchar/kitchendb/data/recipes/apple-crisp.json
{
  "version": "1",
  "name": "Apple Crisp",
  "summary": "",
  "steps": [
    {
      "sectionTitle": "",
      "steps": [
        "Preheat oven to 350 degrees F",
        "Place sliced apples in a 9x13-inch baking dish. Mix white sugar, 1 tablespoon flour, and cinnamon; sprinkle over apples. Pour water evenly over apples.",
        "Combine oats, 1 cup flour, brown sugar, baking powder and baking soda in a bowl. Add melted butter and mix with a fork until crumbly. Sprinkle over apples.",
        "Bake in the oven until top is golden brown and apples are bubbling around the edges, around 45 mins."
      ]
    }
  ],
  "categories": ["dessert", "vegetarian"],
  "ingredients": [
    {
      "sectionTitle": "",
      "ingredients": [
        {
          "amount": [10.0],
          "customUnit": "",
          "ingredient": "cups all-purpose apples",
          "modifier": "peeled, cored and slice"
        },
        {
          "amount": [0.5],
          "unit": "cup",
          "ingredient": "white sugar"
        },
        {
          "amount": [1.0],
          "unit": "tbsp",
          "ingredient": "all-purpose flour"
        },
        {
          "amount": [1.0],
          "unit": "tsp",
          "ingredient": "ground cinnamon"
        },
        {
          "amount": [0.5],
          "unit": "cup",
          "ingredient": "water"
        },
        {
          "amount": [1.0],
          "unit": "cup",
          "ingredient": "quick-cooking oats"
        },
        {
          "amount": [1.0],
          "unit": "cup",
          "ingredient": "all-purpose flour"
        },
        {
          "amount": [1.0],
          "unit": "cup",
          "ingredient": "packed brown sugar"
        },
        {
          "amount": [0.25],
          "unit": "tsp",
          "ingredient": "baking powder"
        },
        {
          "amount": [0.25],
          "unit": "tsp",
          "ingredient": "baking soda"
        },
        {
          "amount": [0.5],
          "unit": "cup",
          "ingredient": "butter",
          "modifier": "melted"
        }
      ]
    }
  ],
  "timestamp": "10/25/2022 20:56:25"
}
